<?xml version="1.0"?>
<robot name="gebot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <xacro:property name="base_width" value="0.9"/>
    <xacro:property name="base_length" value="1.35"/>
    <xacro:property name="base_height" value="0.05"/>

    <xacro:property name="wheel_radius" value="0.125"/>
    <xacro:property name="wheel_width" value="0.08"/>
    <xacro:property name="wheel_ygap" value="-0.04"/>
    <xacro:property name="wheel_zoff" value="0.025"/>
    <xacro:property name="wheel_xoff" value="0.5"/>

    <!-- Defination of some commonly used intertial properties  -->
    <xacro:macro name="box_inertia" params="m w h d">
        <inertial>
            <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
            <mass value="${m}"/>
            <inertia ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0" iyy="${(m/12) * (w*w + d*d)}" iyz="0.0" izz="${(m/12) * (w*w + h*h)}"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertia" params="m r h">
        <inertial>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <mass value="${m}"/>
            <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy = "0" ixz = "0" iyy="${(m/12) * (3*r*r + h*h)}" iyz = "0" izz="${(m/2) * (r*r)}"/>
        </inertial>
    </xacro:macro>

    <!-- Material -->
    <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
    </material>
    <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
    </material>
    <material name="wheel">
        <color rgba="0.15 0.15 0.15 1.0"/>
    </material>
    <material name="myblue">
        <color rgba="0.0 0.0 0.5 1.0"/>
    </material>
    <material name="base">
        <color rgba="0.2 0.05 0.05 1.0"/>
    </material>
    <material name="lidar">
        <color rgba="0.8 0.0 0.0 1.0"/>
    </material>

    <!-- Robot Base -->
    <link name="base_link"/>
 
    <!-- Base_footprint -->
    <!--<link name="base_footprint_joint"/>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>-->

    <!-- Chassis -->
    <link name="base_chassis">
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="base"/>
        </visual>

        <xacro:box_inertia m="1" w="${base_width}" d="${base_length}" h="${base_height}"/><!--3-->
    </link>

    <joint name="base_link_joint" type="fixed">
        <origin xyz="0.5 0.0 0.275" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="base_chassis"/>
    </joint>

    <!-- Wheels -->
    <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
        <link name="${prefix}">
            <collision>
                <!--origin xyz="0 0 0" rpy="${pi/2} 0 0"/-->
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
            </collision>
            <visual>
                <!--origin xyz="0 0 0" rpy="${pi/2} 0 0"/-->
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <material name="wheel"/>
            </visual>
            
            <xacro:cylinder_inertia m="1" r="${wheel_radius}" h="${wheel_width}"/>
        </link>

        <joint name="${prefix}_joint" type="continuous">
            <origin xyz="${x_reflect*wheel_xoff} ${y_reflect*(base_width/2+wheel_ygap)} ${-(wheel_radius+wheel_zoff)}" rpy="${-pi/2} 0 0"/>
            <parent link="base_chassis"/>
            <child link="${prefix}"/>
            <axis xyz="0 0 1"/>
            <dynamics damping="0.2"/>
        </joint>
    </xacro:macro>

    <xacro:wheel prefix="right_wheel" x_reflect="-1" y_reflect="-1" />
    <xacro:wheel prefix="left_wheel" x_reflect="-1" y_reflect="1" />

    <!-- Front Wheel and Joint-->
    <link name="front_wheel">
        <visual>
            <!--origin xyz="0 0 0" rpy="${pi/2} 0 0"/-->
            <geometry>
                <cylinder radius="${wheel_radius}" length="${(wheel_width+0.02)}"/>
            </geometry>
            <material name="wheel"/>
        </visual>
        <collision>
            <!--origin xyz="0 0 0" rpy="${pi/2} 0 0"/-->
            <geometry>
                <cylinder radius="${wheel_radius}" length="${(wheel_width+0.02)}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="1" r="${wheel_radius}" h="${(wheel_width+0.02)}"/><!--5-->
    </link>

    <!--<joint name="front_wheel_joint" type="continuous">
        <axis xyz="0 0 1"/>
        <parent link="base_chassis"/>
        <child link="front_wheel"/>
        <origin xyz="0.475 0.0 -0.145" rpy="${-pi/2} 0 0"/>
        <dynamics damping="0.2" />
    </joint>-->

    <!-- Steering Links and Joints-->
    <link name="steering_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.02"  length="0.93"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.02"  length="0.93"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="1" r="0.02" h="0.93"/><!--0.01-->
    </link>

    <!--<joint name="front_steering_joint" type="revolute">
        <axis xyz="0 0 1"/>
        <limit effort="1000.0" lower="-1.4" upper="1.4" velocity="0.5"/>
        <parent link="base_chassis"/>
        <child link="steering_link"/>
        <origin xyz="0.65 0.0 0.4"/>
    </joint>-->

    <joint name="front_steering_joint" type="fixed">
        <parent link="base_chassis"/>
        <child link="steering_link"/>
        <origin xyz="0.65 0.0 0.4"/>
    </joint>

    <!--<link name="chain_frame">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 ${pi/2} 0.0"/>
            <geometry>
                <cylinder radius="0.01" length="0.2"/>
            </geometry>
            <material name="myblue"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 ${pi/2} 0.0"/>
            <geometry>
                <cylinder radius="0.01" length="0.2"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="0.001" r="0.01" h="0.2"/>
    </link>

    <joint name="steering_gear"  type="fixed">
        <parent link="steering_link"/>
        <child link="chain_frame"/>
        <origin xyz="-0.1 0.0 -0.465"/>
    </joint>-->

    <link name="steering_wheel">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.02" length="0.3"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.02" length="0.3"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="1" r="0.02" h="0.3"/><!--0.005-->
    </link>

    <joint name="steering_wheel_connector" type="fixed">
        <parent link="steering_link"/>
        <child link="steering_wheel"/>
        <origin xyz="0.0 0.0 0.465"/>
    </joint>

    <link name="bearing">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.045" length="0.04"/><!--0.04-->
            </geometry>
            <material name="myblue"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.045" length="0.04"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="1" r="0.0045" h="0.04"/><!--0.001-->
    </link>

    <joint name="bearing_joint"  type="revolute">
        <axis xyz="0 0 1"/>
        <limit effort="1000.0" lower="-1.4" upper="1.4" velocity="0.5"/>
        <parent link="base_chassis"/>
        <child link="bearing"/>
        <origin xyz="0.475 0.0 0.045"/><!--0.045-->
    </joint>

    <link name="bearing_gear">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.02" length="0.195"/>
            </geometry>
            <material name="myblue"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.02" length="0.195"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="1" r="0.02" h="0.195"/><!--0.001-->
    </link>

    <joint name="drive_unit" type="fixed">
        <parent link="bearing"/>
        <child link="bearing_gear"/>
        <origin xyz="0.0 0.0 -0.0975"/>
    </joint>

    <joint name="front_wheel_joint" type="continuous">
        <axis xyz="0 0 1" />
        <parent link="bearing_gear"/>
        <child link="front_wheel"/>
        <origin xyz="0.0 0.0 -0.0975" rpy="${-pi/2} 0.0 0.0"/>
        <!--<origin xyz="0.0 0.0 -0.195" rpy="${-pi/2} 0.0 0.0"/--><!---0.195, -0.115-->
        <!--<origin xyz="0.475 0.0 -0.15" rpy="${-pi/2} 0.0 0.0"/-->
        <dynamics damping="0.2" />
    </joint>

    <!--<joint name="front_wheel_joint" type="continuous">
        <axis xyz="0 0 1" />
        <parent link="chain_frame"/>
        <child link="front_wheel"/>
        <origin xyz="-0.1 0.0 -0.085" rpy="${-pi/2} ${pi/2} 0"/>
        <dynamics damping="0.2" />
    </joint>-->
    
</robot>