controller_manager:
  ros__parameters:
    update_rate: 50 # 50Hz
    use_sim_time: true

    tricycle_steering_controller:
      type: tricycle_steering_controller/TricycleSteeringController

tricycle_steering_controller:
  ros__parameters:

    reference_timeout: 2.0
    front_steering: true 
    open_loop: false 
    velocity_rolling_window_size: 10
    position_feedback: true
    use_stamped_vel: true
    rear_wheels_names: [right_wheel_joint, left_wheel_joint]
    front_wheels_names: [front_steering_joint]  #front_steering_joint

    wheelbase: 1.25
    wheel_track: 0.7
    front_wheels_radius: 0.15
    rear_wheels_radius: 0.15